server:
  port: 1111
spring:
  application:
    name: service-registry
  security:
    user:
      name: user
      password: password
# service registry config
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client: #not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: true #set to true for ZuulProxy
    service-url:
      #defaultZone: http://user:password@localhost:1111/eureka
      defaultZone: http://localhost:1111/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false
zuul:
  sensitiveHeaders:
  routes:
    authentication-service:
      path: /authentication-service/**
      serviceId: authentication-service
      stripPrefix: true
      #url: http://localhost:2222
    user-service: #/user-service/**
      path: /user-service/**
      serviceId: user-service
      stripPrefix: true
      #url: http://localhost:3333
    car-service:
      path: /car-service/**
      serviceId: car-service
      stripPrefix: true
      #url: http://localhost:4444
    rental-service:
      path: /rental-service/**
      serviceId: rental-service
      stripPrefix: true
      #url: http://localhost:5555
ribbon:
  eureka:
    enabled: true #false
  ConnectTimeout: 10000
  ReadTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
